title: Project AIR(AI for Robots)
author: Minsu Jang
email: minsu@etri.re.kr
description: > # this means to ignore newlines until "baseurl:"
  Home of Project AIR

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed